language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql
      php: 5.3
    - env: DBTYPE=sqlite
      php: 5.4
    - env: DBTYPE=mysql
      php: 5.5
  exclude:
    - env: THENEEDFORTHIS=FAIL

before_script: bash .travis.sh

script:
  - cd ../phase3/extensions/SubPageList ; phpunit

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always