language: php

matrix:
  include:
    - env: DBTYPE=mysql; MW=master
      php: 7.3
    - env: DBTYPE=mysql; MW=1.25.6
      php: 5.6
    - env: DBTYPE=sqlite; MW=1.24.0; TYPE=coverage
      php: 5.6
    - env: DBTYPE=mysql; MW=1.23.0
      php: 5.5

install: travis_retry composer self-update

before_script: bash ./build/travis/before_script.sh

script: bash ./build/travis/script.sh

after_success: bash ./build/travis/after_success.sh
